version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: npm"
    labels:
      - "npm"
      - "dependencies"
    reviewers:
      - "block-wallet/backgroundreviewers"